name: skipfish-ci

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the resurrect branch
on:
  push:
    branches: [ resurrect ]
  pull_request:
    branches: [ resurrect ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, ubuntu-18.04, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Ubuntu 22 dependencies
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev libpcre3-dev libidn-dev

    - name: Install Ubuntu 20/18 dependencies
      if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-18.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev libpcre3-dev libidn11-dev

    - name: Install macOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install cmake dpkg openssl pcre libidn

    - name: Run build script
      run: |
        ./build.sh
